---
server:
    install: '1'
    packages: [ruby2.0, ruby2.0-dev, vim, htop, git, redis-server, ruby-dev, zlib1g-dev, libmysqlclient-dev]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
mysql:
    install: '1'
    root_password: '123'
    database: tubetask
    user: tubetask
    password:

